# Generated by Django 6.0.5 on 2026-05-20 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name_en', models.CharField(max_length=150, verbose_name='Name (English)')),
                ('name_bn', models.CharField(max_length=150, verbose_name='Name (Bangla)')),
                ('father_name_en', models.CharField(max_length=150, verbose_name="Father's Name (English)")),
                ('father_name_bn', models.CharField(max_length=150, verbose_name="Father's Name (Bangla)")),
                ('mother_name_en', models.CharField(max_length=150, verbose_name="Mother's Name (English)")),
                ('mother_name_bn', models.CharField(max_length=150, verbose_name="Mother's Name (Bangla)")),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('religion', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('mobile', models.CharField(max_length=15)),
                ('guardian_mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('present_address', models.JSONField(default=dict, help_text="Format: {'village': '', 'post_office': '', 'post_code': '', 'upazila': '', 'district': '', 'division': ''}")),
                ('permanent_address', models.JSONField(default=dict, help_text="Format: {'village': '', 'post_office': '', 'post_code': '', 'upazila': '', 'district': '', 'division': ''}")),
                ('ssc_year', models.IntegerField(verbose_name='SSC Passing Year')),
                ('ssc_gpa', models.FloatField(verbose_name='SSC GPA')),
                ('department', models.CharField(choices=[('CST', 'Computer Science & Technology'), ('Civil', 'Civil Engineering'), ('Electrical', 'Electrical Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Power', 'Power Engineering'), ('Electronics', 'Electronics Engineering'), ('Architecture', 'Architecture'), ('RAC', 'RAC')], max_length=50)),
                ('session', models.CharField(help_text='e.g., 2023-24', max_length=20)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')], max_length=10)),
                ('shift', models.CharField(choices=[('1st', '1st Shift'), ('2nd', '2nd Shift')], max_length=10)),
                ('roll_no', models.CharField(max_length=20, unique=True, verbose_name='Polytechnic Roll No')),
                ('cub_experience', models.BooleanField(default=False)),
                ('cub_badge', models.CharField(blank=True, max_length=100, null=True)),
                ('scout_experience', models.BooleanField(default=False)),
                ('scout_badge', models.CharField(blank=True, max_length=100, null=True)),
                ('other_skills', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rover_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
