# Generated by Django 6.0.4 on 2026-05-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0004_feestructure_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverprofile',
            name='department',
            field=models.CharField(choices=[('CST', 'Computer Science & Technology'), ('Civil', 'Civil Technology'), ('Electrical', 'Electrical Technology'), ('Mechanical', 'Mechanical Technology'), ('Power', 'Power Technology'), ('Electronics', 'Electronics Technology'), ('Architecture', 'Architecture Technology'), ('RAC', 'RAC Technology')], max_length=50),
        ),
    ]
