# Generated by Django 6.0.4 on 2026-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0006_alter_roverprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverprofile',
            name='blood_group',
            field=models.CharField(choices=[('', '-- Select Blood Group --'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='roverprofile',
            name='department',
            field=models.CharField(choices=[('', '-- Select Session --'), ('CST', 'Computer Science & Technology'), ('Civil', 'Civil Technology'), ('Electrical', 'Electrical Technology'), ('Mechanical', 'Mechanical Technology'), ('Power', 'Power Technology'), ('RAC', 'RAC Technology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roverprofile',
            name='semester',
            field=models.CharField(choices=[('', '-- Select Semester --'), ('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')], max_length=10),
        ),
        migrations.AlterField(
            model_name='roverprofile',
            name='shift',
            field=models.CharField(choices=[('', '-- Select Shift --'), ('1st', '1st Shift'), ('2nd', '2nd Shift')], max_length=10),
        ),
    ]
