# Generated by Django 6.0.5 on 2026-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0007_alter_roverprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('GP', 'Group President (গ্রুপ সভাপতি)'), ('GS', 'Group Secretary (গ্রুপ সম্পাদক)'), ('RSL', 'Rover Scout Leader (RSL)'), ('SRM', 'Senior Rover Mate (SRM)')], max_length=3)),
                ('image', models.ImageField(upload_to='leaders/')),
                ('phone', models.CharField(blank=True, help_text='e.g., +88017XXXXXXXX', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order to display (e.g., 1 for President, 2 for Secretary...)')),
            ],
        ),
    ]
