# Generated by Django 6.0.5 on 2026-05-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0008_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoverRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Rank Title')),
            ],
            options={
                'verbose_name_plural': 'Rover Ranks',
            },
        ),
        migrations.CreateModel(
            name='RoverStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Stage Title')),
            ],
            options={
                'verbose_name_plural': 'Rover Stages',
            },
        ),
        migrations.AddField(
            model_name='roverprofile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rovers.roverrank', verbose_name='Current Rank'),
        ),
        migrations.AddField(
            model_name='roverprofile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rovers.roverstage', verbose_name='Current Stage'),
        ),
    ]
